// Generated by gencpp from file erp_com/Status.msg
// DO NOT EDIT!


#ifndef ERP_COM_MESSAGE_STATUS_H
#define ERP_COM_MESSAGE_STATUS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace erp_com
{
template <class ContainerAllocator>
struct Status_
{
  typedef Status_<ContainerAllocator> Type;

  Status_()
    : control_mode(0)
    , e_stop(false)
    , gear(0)
    , speed(0)
    , steer(0)
    , brake(0)
    , encoder(0)
    , alive(0)  {
    }
  Status_(const ContainerAllocator& _alloc)
    : control_mode(0)
    , e_stop(false)
    , gear(0)
    , speed(0)
    , steer(0)
    , brake(0)
    , encoder(0)
    , alive(0)  {
  (void)_alloc;
    }



   typedef int8_t _control_mode_type;
  _control_mode_type control_mode;

   typedef uint8_t _e_stop_type;
  _e_stop_type e_stop;

   typedef uint8_t _gear_type;
  _gear_type gear;

   typedef uint8_t _speed_type;
  _speed_type speed;

   typedef int32_t _steer_type;
  _steer_type steer;

   typedef uint8_t _brake_type;
  _brake_type brake;

   typedef int32_t _encoder_type;
  _encoder_type encoder;

   typedef uint8_t _alive_type;
  _alive_type alive;





  typedef boost::shared_ptr< ::erp_com::Status_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::erp_com::Status_<ContainerAllocator> const> ConstPtr;

}; // struct Status_

typedef ::erp_com::Status_<std::allocator<void> > Status;

typedef boost::shared_ptr< ::erp_com::Status > StatusPtr;
typedef boost::shared_ptr< ::erp_com::Status const> StatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::erp_com::Status_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::erp_com::Status_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::erp_com::Status_<ContainerAllocator1> & lhs, const ::erp_com::Status_<ContainerAllocator2> & rhs)
{
  return lhs.control_mode == rhs.control_mode &&
    lhs.e_stop == rhs.e_stop &&
    lhs.gear == rhs.gear &&
    lhs.speed == rhs.speed &&
    lhs.steer == rhs.steer &&
    lhs.brake == rhs.brake &&
    lhs.encoder == rhs.encoder &&
    lhs.alive == rhs.alive;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::erp_com::Status_<ContainerAllocator1> & lhs, const ::erp_com::Status_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace erp_com

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::erp_com::Status_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::erp_com::Status_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::erp_com::Status_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::erp_com::Status_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::erp_com::Status_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::erp_com::Status_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::erp_com::Status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c9878ccc909e763ca6b607c34a8914ba";
  }

  static const char* value(const ::erp_com::Status_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc9878ccc909e763cULL;
  static const uint64_t static_value2 = 0xa6b607c34a8914baULL;
};

template<class ContainerAllocator>
struct DataType< ::erp_com::Status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "erp_com/Status";
  }

  static const char* value(const ::erp_com::Status_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::erp_com::Status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 control_mode\n"
"bool e_stop\n"
"uint8 gear\n"
"uint8 speed\n"
"int32 steer\n"
"uint8 brake\n"
"int32 encoder\n"
"uint8 alive\n"
;
  }

  static const char* value(const ::erp_com::Status_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::erp_com::Status_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.control_mode);
      stream.next(m.e_stop);
      stream.next(m.gear);
      stream.next(m.speed);
      stream.next(m.steer);
      stream.next(m.brake);
      stream.next(m.encoder);
      stream.next(m.alive);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Status_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::erp_com::Status_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::erp_com::Status_<ContainerAllocator>& v)
  {
    s << indent << "control_mode: ";
    Printer<int8_t>::stream(s, indent + "  ", v.control_mode);
    s << indent << "e_stop: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.e_stop);
    s << indent << "gear: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.gear);
    s << indent << "speed: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.speed);
    s << indent << "steer: ";
    Printer<int32_t>::stream(s, indent + "  ", v.steer);
    s << indent << "brake: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.brake);
    s << indent << "encoder: ";
    Printer<int32_t>::stream(s, indent + "  ", v.encoder);
    s << indent << "alive: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.alive);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ERP_COM_MESSAGE_STATUS_H
